version: "3.9"

services:
  mongodb:
    container_name: digitro-mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db

  mongodb-express:
    image: mongo-express
    container_name: digitro-mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: digitro-mongodb

  app:
    build: .
    container_name: digitro
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  mongodb: {}
